server:
  port: 8082
#  port: 0
  servlet:
    context-path: /user-service
spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
