server:
  port: 8081
  #  port: 0
  servlet:
    context-path: /device-service
spring:
  application:
    name: device-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
