version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Pa$$-123
      - MYSQL_DATABASE=smartHome
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Pa$$-123
    volumes:
      - /data/mysql
    ports:
      - 3333:3306
    container_name: kamienica-db
  kamienica-app:
    image: kamienica-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8082:8082
    volumes:
      - /data/spring-boot-app
    container_name: kamienica-app